[build-system]
requires = [
  "setuptools",
  "build",
  "pytest",
  "pdoc"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
license-files = []

[project]
name = "whitebox-adversarial-toolbox"
version = "0.2.4"
authors = [
  { name="wuhanstudio", email="wuhanstudios@gmail.com" },
]
maintainers = [
  { name="wuhanstudio", email="wuhanstudios@gmail.com" },
]
description = "WHite-box Adversarial Toolbox (WHAT) - Python Library for Deep Learning Security"
readme = "README.md"
license = {text = "MIT License"}
requires-python = ">=3.6"
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy>=1.18.0,<1.20",
    "tqdm",
    "six",
    "setuptools",
    "torch<2.0",
    "torchvision",
    "opencv-python",
    "scikit-image",
    "tensorflow",
    "keras==2.4.3",
    "h5py==2.10.0",
    "protobuf<3.20",
    "matplotlib",
    "pandas",
    "click",
    "progressbar",
    "loguru",
    "psutil",
    "pycocotools",
    "tabulate",
]

[project.scripts]
what = "what._main:main"

[project.urls]
"Homepage" = "https://github.com/wuhanstudio/whitebox-adversarial-toolbox"
"Bug Tracker" = "https://github.com/wuhanstudio/whitebox-adversarial-toolbox/issues"

[dependency-groups]
dev = [
    "pdoc>=0.4.1",
    "pytest>=7.0.1",
    "setuptools>=59.6.0",
    "build",
]
